apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config-file
  namespace: forensic-platform
data:
  config.yaml: |
    server:
      gatewayPort: 8080
    database:
      dsn: "postgresql://PLACEHOLDER_USER:PLACEHOLDER_DB_PASS@PLACEHOLDER_HOST:5432/postgres?sslmode=require"
    kafka:
      brokers: ["forensic-kafka-ai-log-analyser.l.aivencloud.com:19800"]
    redis:
      url: "feasible-bedbug-40106.upstash.io:6379"
    logging:
      level: "info"
