apiVersion: apps/v1
kind: Deployment
metadata:
  name: workforce-service
  namespace: forensic-platform
  labels:
    app: workforce-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workforce-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workforce-service
    spec:
      containers:
      - name: workforce-service
        image: acrlogpraveen99.azurecr.io/workforce-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: log-analyzer-config
        - secretRef:
            name: forensic-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: workforce-service
  namespace: forensic-platform
spec:
  selector:
    app: workforce-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
