# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ai_analysis_pb2 as ai__analysis__pb2


class AIAnalysisServiceStub(object):
    """--- SERVICES ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeLogs = channel.unary_unary(
                '/loganalyzer.AIAnalysisService/AnalyzeLogs',
                request_serializer=ai__analysis__pb2.LogBatch.SerializeToString,
                response_deserializer=ai__analysis__pb2.AnalysisResponse.FromString,
                )
        self.StreamAnalysis = channel.stream_stream(
                '/loganalyzer.AIAnalysisService/StreamAnalysis',
                request_serializer=ai__analysis__pb2.LogEntry.SerializeToString,
                response_deserializer=ai__analysis__pb2.AnomalyResult.FromString,
                )
        self.GenerateReport = channel.unary_unary(
                '/loganalyzer.AIAnalysisService/GenerateReport',
                request_serializer=ai__analysis__pb2.ReportRequest.SerializeToString,
                response_deserializer=ai__analysis__pb2.IncidentReport.FromString,
                )
        self.ChatAboutLogs = channel.unary_stream(
                '/loganalyzer.AIAnalysisService/ChatAboutLogs',
                request_serializer=ai__analysis__pb2.ChatRequest.SerializeToString,
                response_deserializer=ai__analysis__pb2.ChatResponse.FromString,
                )
        self.PredictFailures = channel.unary_unary(
                '/loganalyzer.AIAnalysisService/PredictFailures',
                request_serializer=ai__analysis__pb2.PredictionRequest.SerializeToString,
                response_deserializer=ai__analysis__pb2.PredictionResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/loganalyzer.AIAnalysisService/HealthCheck',
                request_serializer=ai__analysis__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ai__analysis__pb2.HealthCheckResponse.FromString,
                )


class AIAnalysisServiceServicer(object):
    """--- SERVICES ---

    """

    def AnalyzeLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAnalysis(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatAboutLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictFailures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeLogs,
                    request_deserializer=ai__analysis__pb2.LogBatch.FromString,
                    response_serializer=ai__analysis__pb2.AnalysisResponse.SerializeToString,
            ),
            'StreamAnalysis': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAnalysis,
                    request_deserializer=ai__analysis__pb2.LogEntry.FromString,
                    response_serializer=ai__analysis__pb2.AnomalyResult.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=ai__analysis__pb2.ReportRequest.FromString,
                    response_serializer=ai__analysis__pb2.IncidentReport.SerializeToString,
            ),
            'ChatAboutLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatAboutLogs,
                    request_deserializer=ai__analysis__pb2.ChatRequest.FromString,
                    response_serializer=ai__analysis__pb2.ChatResponse.SerializeToString,
            ),
            'PredictFailures': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictFailures,
                    request_deserializer=ai__analysis__pb2.PredictionRequest.FromString,
                    response_serializer=ai__analysis__pb2.PredictionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ai__analysis__pb2.HealthCheckRequest.FromString,
                    response_serializer=ai__analysis__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loganalyzer.AIAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIAnalysisService(object):
    """--- SERVICES ---

    """

    @staticmethod
    def AnalyzeLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/loganalyzer.AIAnalysisService/AnalyzeLogs',
            ai__analysis__pb2.LogBatch.SerializeToString,
            ai__analysis__pb2.AnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamAnalysis(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/loganalyzer.AIAnalysisService/StreamAnalysis',
            ai__analysis__pb2.LogEntry.SerializeToString,
            ai__analysis__pb2.AnomalyResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/loganalyzer.AIAnalysisService/GenerateReport',
            ai__analysis__pb2.ReportRequest.SerializeToString,
            ai__analysis__pb2.IncidentReport.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChatAboutLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/loganalyzer.AIAnalysisService/ChatAboutLogs',
            ai__analysis__pb2.ChatRequest.SerializeToString,
            ai__analysis__pb2.ChatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictFailures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/loganalyzer.AIAnalysisService/PredictFailures',
            ai__analysis__pb2.PredictionRequest.SerializeToString,
            ai__analysis__pb2.PredictionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/loganalyzer.AIAnalysisService/HealthCheck',
            ai__analysis__pb2.HealthCheckRequest.SerializeToString,
            ai__analysis__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AlertServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendAlert = channel.unary_unary(
                '/loganalyzer.AlertService/SendAlert',
                request_serializer=ai__analysis__pb2.AlertRequest.SerializeToString,
                response_deserializer=ai__analysis__pb2.AlertResponse.FromString,
                )


class AlertServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAlert,
                    request_deserializer=ai__analysis__pb2.AlertRequest.FromString,
                    response_serializer=ai__analysis__pb2.AlertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loganalyzer.AlertService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AlertService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/loganalyzer.AlertService/SendAlert',
            ai__analysis__pb2.AlertRequest.SerializeToString,
            ai__analysis__pb2.AlertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
